service: cloudfront-invalidate-dist

provider:
  name: aws
  runtime: ${opt:runtime, 'nodejs10.x'}
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "codepipeline:PutJobFailureResult"
        - "codepipeline:PutJobSuccessResult"
        - "cloudfront:CreateInvalidation"
      Resource: "*"

functions:
  invalidate:
    handler: handler.handler
